plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'com.diffplug.spotless' version '8.10.3'
	id 'checkstyle'  // pas de verison car il fait déjà partie de gradle
}

group = 'fr.foyer'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}

spotless{
	java {
        googleJavaFormat('1.30.0')  // Utilise google-java-format pour reformater le code Java.
        removeUnusedImports()  // supprime des imports inutilisés
        trimTrailingWhitespace()  // enlève les espaces inutiles à la fin des lignes
        endWithNewline()  // s'assure que les fichiers se terminent proprement par une nouvelle ligne.
    }
}

checkstyle {
    toolVersion = '14.3.0'
}